### ISSUE TITLE
这个跟mock有何关系？

### ISSUE THREAD

**Issue by Popxie** [AnonymousArthur/expedited-mock#1]
infoq过来的，下载了源码，项目也跑起来了，可是还是没有看明白 你想表达什么、这个mock又有什么关系呢？ = = 可否在详细点呀

**Comment by AnonymousArthur** [comment]
你好，在前端做这样的mock是为了在没有后端开发的条件下，还原最接近真实业务场景。如果单独mock static API的话，可能不能很好地还原业务的流程。比如用户新建一个item之后，在static api上不能实时反映出用户新建的这个item的详细属性，那么在接下来的流程中，代入感就差了很多。

**Comment by Popxie** [comment]
额。说实话，还没没有看懂你这的写的，想了解下。（其实是没弄懂这样写的作用是什么点来点去也没发现有ajax请求）


| |
KaKa
前端工程师
|
|
mrxiehuaqiang@163.com
|

签名由 网易邮箱大师 定制

在2020年05月07日 10:46，Arthur 写道：

你好，在前端做这样的mock是为了在没有后端开发的条件下，还原最接近真实业务场景。如果单独mock static API的话，可能不能很好地还原业务的流程。比如用户新建一个item之后，在static api上不能实时反映出用户新建的这个item的详细属性，那么在接下来的流程中，代入感就差了很多。
